// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2du3W3KBkL9ep0v9-ZMeQW-Nfenp6N7I',
    appId: '1:778884543956:web:66e5c19d73efefdde09241',
    messagingSenderId: '778884543956',
    projectId: 'switch-4215d',
    authDomain: 'switch-4215d.firebaseapp.com',
    storageBucket: 'switch-4215d.firebasestorage.app',
    measurementId: 'G-0S0N5F3NV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbQFkQ9z9DqLPAYtSO1f7lTG-jsd4UZpk',
    appId: '1:778884543956:android:687b226a16924624e09241',
    messagingSenderId: '778884543956',
    projectId: 'switch-4215d',
    storageBucket: 'switch-4215d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEYtGWetESExSGcZquQQbRfzS7Mvx4F7c',
    appId: '1:778884543956:ios:ea1e583717e4e7d1e09241',
    messagingSenderId: '778884543956',
    projectId: 'switch-4215d',
    storageBucket: 'switch-4215d.firebasestorage.app',
    iosBundleId: 'com.example.switchTestTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEYtGWetESExSGcZquQQbRfzS7Mvx4F7c',
    appId: '1:778884543956:ios:ea1e583717e4e7d1e09241',
    messagingSenderId: '778884543956',
    projectId: 'switch-4215d',
    storageBucket: 'switch-4215d.firebasestorage.app',
    iosBundleId: 'com.example.switchTestTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2du3W3KBkL9ep0v9-ZMeQW-Nfenp6N7I',
    appId: '1:778884543956:web:02bb98ae1c3e7600e09241',
    messagingSenderId: '778884543956',
    projectId: 'switch-4215d',
    authDomain: 'switch-4215d.firebaseapp.com',
    storageBucket: 'switch-4215d.firebasestorage.app',
    measurementId: 'G-2ZTCY9H14T',
  );
}
